
server:
  port: ${server_port:8080}

eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}

spring:
  application:
    name: a-bootiful-client
#  devtools:
#    remote:
#      secret: mysecret

#management:
#  security:
#    enabled: false